Calvin openai streamlit app
revanthsenthil/promptmove-ai pull request #10
Opened 2024-02-23 23:36 UTC by MadSons

I have an awesome chatbot with memory of details and function about a house.

Just need an openai API key passed as an environment variable called OPENAI_API_KEY

2024-02-23 23:37 UTC, MadSons commented
Real progress has been made

2024-02-23 23:48 UTC, MadSons commented
success

2024-02-24 03:30 UTC, revanthsenthil reviewed
@MadSons Are the functions to interact with the environment something that were generated, or you used it from VirtualHome documentation? Also yeah I don't know how I missed that but we definitely should not be committing pvt keys to the repo lol.

2024-02-24 03:32 UTC, MadSons commented
The json file and the python file I just made up off the top of my head as proof of concept. The assistant has access to both and can understand the tools and data it has access to via file upload.

2024-02-24 03:50 UTC, revanthsenthil requested changes
@MadSons can you move these examples and house_information into scripts or tests, instead of src? Let's maintain src for full build updates and direct enhancements. Once we know exactly what works with the codegen, we can put that codegen script into src as a separate dir with sub-files.

2024-02-24 23:49 UTC, revanthsenthil approved these changes
Looks good for now but we definitely need to improve it. To refer to the kind of inputs that VirtualHome needs, refer this: https://github.com/revanthsenthil/promptmove-ai/blob/f20d72379e43d6babec8fda7f50cd91d0ee83823/scripts/test.py#L97C1-L104C4

2024-02-24 23:50 UTC, merged